### ISSUE TITLE
Is it possible to apply various block_sizes to the conv2d layer at this time?

### ISSUE THREAD

**Issue by cha-noong** [tensorflow/model-optimization#708] opened 2021-05-14 09:54 UTC
**System information**

- TensorFlow version (you are using): 2.6.0-nightly
- Are you willing to contribute it (Yes/No): yes

**Motivation**

I want to apply sparsity pruning to MobilenetV2 like a fast-sparse convnet pre-trained model.
I checked that the default block_size of (1,1) works for the CNN model, but there was no latency improvement.

I tried to apply the block size as (1x4), (1x8), etc., as it seems that there will be a benefit in speed, but the following error occurs in conv2d layer.

ValueError: Block Sparsity can only be used for layers which have 2-dimensional weights.

mnist example
https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/examples/sparsity/keras/mnist/mnist_e2e.py

Even in the mnist example, pruning is performed only on the dense layer, not the conv2d layer. Is it possible to apply various block_sizes to the Cnn layer at this time?

If possible, could you provide me examples or a guideline?

**Comment by daverim** [comment] 2021-05-17 01:35
At this time, only 2d weights can use 2d block-sizes via prune_low_magnitude. 

@liyunlu0618, do you have an idea as to if this should be on the roadmap?

**Comment by daverim** [comment] 2021-05-17 01:58
Whoops, sorry, this is a duplicate of #634.

**Closed by daverim** 2021-05-17 01:58 UTC
Labels: feature request
