### ISSUE TITLE
Getting an error when creating the .tflite file

### ISSUE THREAD

**Issue by marjanemd** [tensorflow/model-optimization#412] opened 2020-05-30 02:02 UTC
Hello,

I am getting an error while creating the tflite file in the following line of the code:

`tflite_model = converter.convert()`

The error is:
tensorflow/lite/kernels/quantize.cc:110 affine_quantization->scale->size == 1 was not true.Node number 0 (QUANTIZE) failed to prepare.

When saving the Keras model, there is an input layer created, which does not have the scale and offset for quantizing, I have tried different methods but it is generated automatically. Any help is much appreciated.

TensorFlow Model Optimization version (installed from source or binary):
'2.3.0-dev20200528'

Python version:
3

Best,
Marjan

**Comment by nutsiepully** [comment] 2020-06-02 23:27
Could you please add your the code for your TF model, and the full tflite converter params? It isn't feasible to debug the model without looking at it.

This error is typically thrown when the quantization params have an incorrect scale dimension.

**Comment by alanchiao** [comment] 2020-06-03 00:35
Please also include the TF version (and generally follow the [template](https://github.com/tensorflow/model-optimization/issues/new?assignees=&labels=bug&template=bug_report.md)).

**Comment by marjanemd** [comment] 2020-06-03 01:23
@nutsiepully 
I am just using the keras model for tflite converter as:

`converter=tf.lite.TFLiteConverter.from_keras_model(model).`
Following shows the keras model, and as you can see there are two cells as InputLayer and QuantizeLayer which do not have the quantization values. I know that the issue is comming from here, but not sure how to prevent this. The model seems right to me and I don't get the reason of first 2 cells being created.

![Screen Shot 2020-06-02 at 6 10 55 PM](https://user-images.githubusercontent.com/38959661/83584586-74696700-a4fc-11ea-8072-3f095b53785e.png)

The model is build as the following code:

`model= Sequential([
quantize.quantize_annotate_layer(Conv2D(64,1,input_shape=(55,40,1),use_bias=True,activation="relu")),
MaxPooling2D(2,2),
 Conv2D(64,(1,1),use_bias=True,activation="relu"),
Flatten(),
Dense(2,use_bias=True),
Softmax() ])`

`model = quantize.quantize_apply(model)`


@alanchiao As I had mentioned before my TF version is : 2.3.0

**Comment by lorenz0890** [comment] 2020-07-31 15:24
I have this problem as well. It occurs when quantizing a pretrained mobilenetv2 using tf.float16 quantization. Int8 quantization works well in the same setup though.

**Comment by KeyKy** [comment] 2020-09-08 05:29
I get the same problem when running the mnist_cnn_cont_quant.py example

**Comment by nutsiepully** [comment] 2020-09-08 18:25
@lorenz0890 - QAT currently only supports the int8 quantization spec. So TFLite conversion won't be able to convert a QAT model when the `target_spec` is tf.float16. You don't need QAT with float16 actually. The loss recovery is useful for 8-bits. 16 bits are large enough for model information to be preserved.

**Comment by malimora** [comment] 2020-10-07 07:53
@nutsiepully I am getting same error when trying to convert QAT pretrained Mobilenetv2 keras model to tflite with ```converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]```. My minimal code:
```python
model = keras.applications.MobileNetV2(weights='imagenet')
model.compile(...)
    
quantize_model = tfmot.quantization.keras.quantize_model
q_model = quantize_model(model)
q_model.compile(...)

converter = tf.lite.TFLiteConverter.from_keras_model(q_model)
converter.representative_dataset = my_representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
# error generated when calling convert(): RuntimeError: tensorflow/lite/kernels/quantize.cc:111 affine_quantization->scale->size == 1 was not true.Node number 0 (QUANTIZE) failed to prepare.
converter.convert()

def my_representative_dataset_gen():
       # for image in my_dataset:
           # yield image

```

**Comment by car1hsiung** [comment] 2020-10-16 06:18
@nutsiepully INT8 TFLite is not work, but FP32 TFLite is work.

**Describe the bug**

1. Can not convert quantization aware model to INT8 TFLite.
2. `converter.inference_input_type = tf.int8` and `converter.inference_output_type = tf.int8` are not work.
3. FP32 TFLite is work.

**System information**

TensorFlow version: tf-nightly (2.4.0-dev20201015)

TensorFlow Model Optimization version: 0.5.0

Python version: 3.6.9

**Describe the expected behavior**

Convert INT8 TFLite sucessfully.

**Code to reproduce the issue**

Please check the [gist](https://colab.research.google.com/drive/14glMvUN1H2PZHB2VPOwX9sZX9E2RNu0J?usp=sharing) here.

Thanks in advance.

**Comment by car1hsiung** [comment] 2020-12-09 06:00
> @nutsiepully FP32 TFLite is work, but INT8 TFLite is not work.
> 
> **Describe the bug**
> 
>     1. Can not convert quantization aware model to INT8 TFLite.
> 
>     2. `converter.inference_input_type = tf.int8` and `converter.inference_output_type = tf.int8` are not work.
> 
>     3. FP32 TFLite is work.
> 
> 
> **System information**
> 
> TensorFlow version: tf-nightly (2.4.0-dev20201015)
> 
> TensorFlow Model Optimization version: 0.5.0
> 
> Python version: 3.6.9
> 
> **Describe the expected behavior**
> 
> Convert INT8 TFLite sucessfully.
> 
> **Code to reproduce the issue**
> 
> Please check the [gist](https://colab.research.google.com/drive/14glMvUN1H2PZHB2VPOwX9sZX9E2RNu0J?usp=sharing) here.
> 
> Thanks in advance.

It worked with tf 2.4.0rc1:

[https://github.com/tensorflow/tensorflow/issues/44079](https://github.com/tensorflow/tensorflow/issues/44079)

[https://github.com/tensorflow/tensorflow/issues/42082](https://github.com/tensorflow/tensorflow/issues/42082)

**Comment by teijeong** [comment] 2021-04-16 06:51
Hi @marjanemd , closing this as it seems to be resolved. please reopen or file a new one if this is still a problem.

**Closed by teijeong** 2021-04-16 06:51 UTC
Labels: bug, technique:qat
